### ISSUE TITLE
How to modify part() to read more than 4 vertices?

### ISSUE THREAD

**Issue by purijs** [cogeotiff/rio-tiler#218]
Is there a way to modify the following:

```
with COGReader("myfile.tif") as cog:
    data, mask = cog.part((10, 10, 20, 20))
```

Into something that can accept `polygon` and not just a `square/rectangle`

**Comment by vincentsarago** [comment]
Hi @purijs 
There is way to do this by using the CUTLINE options passed via the vrt_options 
Ref: https://gdal.org/api/gdalwarp_cpp.html?highlight=vrt#structGDALWarpOptions

It’s kind of tricky because you’ll need 
1. To get the bounding box of the geometry 
2. Create a WKT representing your geometry withing the bbox BUT IN PIXEL COORDINATES 

@kylebarron has been working on this topic and we talked about bringing helper function in rio-tiler to create this WKT cutline
