### ISSUE TITLE
Add COG overview information to `info`?

### ISSUE THREAD

**Issue by kylebarron** [cogeotiff/rio-tiler#304]
Add it here? https://github.com/cogeotiff/rio-tiler/blob/702b7c973b533c040f00e8eb73baceda5fcf292a/rio_tiler/io/cogeo.py#L178-L220

Would allow an application to deduce appropriate zoom levels from titiler's `/cog/info` response.

**Comment by vincentsarago** [comment]
> Would allow an application to deduce appropriate zoom levels from titiler's /cog/info response.

@kylebarron I'm not sure to get this. the minzoom/maxzoom is already in the `info()` response but the TiTiler `/info` endpoint ignores it https://github.com/developmentseed/titiler/blob/master/titiler/endpoints/factory.py#L170 because the zooms are linked to a TMS grid which is not an input of the `/info` endpoint 

That's said, I'm ok adding more `low level dataset` info like overview level

**Comment by vincentsarago** [comment]
I added the overview decimation levels in https://github.com/cogeotiff/rio-tiler/pull/387, I think this is enough for now!
