### ISSUE TITLE
Avoid reprojection (WarpedVRT) when not needed

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#485]
when we created rio-tiler we had 2 main requirement:
- get a mercator tile from any raster
- be able to override nodata value (for Landsat data)

Because of this we used rasterio [WarpedVRT](https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/reader.py#L79) which is really convenient. 

Info from https://github.com/OSGeo/gdal/issues/5343, seems to indicate that we should not used WarpedVRT when no reprojection is not needed (for speed and for resampling artefacts).

**Comment by mdsumner** [comment]
fwiw it's certainly possible to use the warper to give exactly what the RasterIO function does, you need an "aligned extent" - the exact numeric equivalent of what the line/col (window offset,size) inputs to RasterIO use - and a nrow/ncol that is an integer divisor of the source, and resample = "near".  

There are advantages because you can have multiple inputs from various sources too. I'm just saying this here as I'm interested in cross-community shared understanding, I realize it's not exactly relevant right here. But, I'm looking for interested allies across R and Python and GDAL here. :)  Finaly, I have a nascent PR-for-GDAL  that I'm planning, I'd like the warper to have a "snap" option - so that it literally does what the analagous call to RasterIO would do (snap to pixel alignment), not snap to exact target extent.
