### ISSUE TITLE
More colormap options! 

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler#91]
With #90 @DanSchoppe added a third `colormap` to rio-tiler. While this is awesome, I think rio-tiler could do more for allowing user to define custom colormap.

**colormap** are used when translating a one band data array to the image format using the new `array_to_image`(using GDAL using a simple translation:
https://github.com/cogeotiff/rio-tiler/blob/e512d8441e7ebb460d074a4a98a76051ad983b73/rio_tiler/utils.py#L386

So here ☝️ a `rio_tiler.utils.array_to_image` compatible colormap object is usually an array of shape `(256, 3)`
```python
c = get_colormap(format="gdal")
print(c.shape)
 (256, 3)
print(c)
[
  [255 255 255]
  [250 250 250]
  [246 246 246]
  [242 242 242]
  ...
  [255   1 191]
  [255   1 207]
  [255   1 223]
  [255   1 239]
]
```

I first though we could have used a custom dict like
```python
{
    0: [255, 255, 255],
    100: [255,   1, 191],
    ...
}
```
~to create a colormap for`discrete` values, but dict are not hashable so the current code in `rio_tiler.utils.array_to_image` won't work.~

I do love the dict option for colormap (like Rasterio use https://github.com/mapbox/rasterio/blob/960a906dad2a4e426387ce048a52c6e90afdcd2b/docs/topics/color.rst#writing-colormaps) so I first check if we can maybe change the `rio_tiler.utils.get_colormap` function to have to return a dictionary colormap (because it seems to be the default format for GDAL) and in the same time adapt the `rio_tiler.utils.array_to_image` to work with dict. 

In a second time we could add another utility function to create colormaps, it seems that matplotlib has some functionality but I'm not sure we should had more required module to rio-tiler.

**Comment by DanSchoppe** [comment]
Thanks Vincent for getting this conversation started.

I've been thinking about this for awhile. At a high level, I'm hoping there's a way to adapt the combination of [rio-tiler + REST API (like remotepixel-tiler)] so they can accept a colormap at tile request time, rather than having to reference a predefined colormap by name. My thinking has been coming at this from an API networking level, so I'm going to start brainstorming from there.

- [3 x 256] array is too large to pass as a query parameter, so if we stuck with our current colormap data structure, passing a full colormap at request time would probably be done via POST message body. At least it would compress well.
- Perhaps there's an elegant way to reduce the [3 x 256] array colormap schema to something more concise. You mentioned matplotlib, and I happened to find the same project for inspiration. If there's a sufficiently concise way to describe a colormap, perhaps it would be palatable to include a colormap-producing description as a query param. Here's the matplotlib colormap definitions for reference: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_cm.py
I'm not sure there will be a flexible enough way to concisely describe colormaps without allowing the user to simply provide the full mapping for every index. For example, the colormap in #90 was produced by programmatically interpolating between colors in HSV colorspace.

Based on your above comment, our two goals for this issue may not have any overlap, but hopefully we can come up with some flexible way to better extend colormap support.

**Comment by vincentsarago** [comment]
For reference the excellent Marblecutter use Matplotlib for color ramps.  https://github.com/mojodna/marblecutter/blob/master/marblecutter/formats/color_ramp.py

Matplotlib is an optional requirement in marblecutter https://github.com/mojodna/marblecutter/blob/master/setup.py#L29

**Comment by vincentsarago** [comment]
> [3 x 256] array is too large to pass as a query parameter, so if we stuck with our current colormap data structure, passing a full colormap at request time would probably be done via POST message body. At least it would compress well.

Nice thing about rio-tiler, is that it's designed to be implementation agnostic to be used behind API or other functions (like rio-glui, remotepixel-tiler ...). Passing a 3x256 array or dict via a POST message shouldn't be a problem for you API. But I agree we need a tool which can create color map from a colormap definition (e.g. passing min/max color) 

> Perhaps there's an elegant way to reduce the [3 x 256] array colormap schema to something more concise. You mentioned matplotlib, and I happened to find the same project for inspiration. If there's a sufficiently concise way to describe a colormap, perhaps it would be palatable to include a colormap-producing description as a query param. Here's the matplotlib colormap definitions for reference: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_cm.py
I'm not sure there will be a flexible enough way to concisely describe colormaps without allowing the user to simply provide the full mapping for every index. For example, the colormap in #90 was produced by programmatically interpolating between colors in HSV colorspace.

Well as mentioned earlier, rio-tiler is agnostic, user could totally add Matplotlib to its API and apply the colormap using something else that `rio-tiler.utils.array_to_image` function. Meaning: I think at one point I'd like to keep rio-tiler as simple as possible so we focus on tiling performances and not on third party implementation (e.g: serving images).

**Comment by vincentsarago** [comment]
FYI: in #92 I've updated `rio_tiler.utils.array_to_image` to allow discrete colormap passed as dictionary

**Comment by vincentsarago** [comment]
👋 @dionhaefner I have checking the colormap implementation in terracotta and I kinda like that you are storing numpy array directly as `.npy` files (and that you provide a lot of different cmap). I was then wondering how you created those colormaps ?

**Comment by dionhaefner** [comment]
Here's the script:

https://github.com/DHI-GRAS/terracotta/blob/master/terracotta/cmaps/generate_cmaps.py

**Comment by vincentsarago** [comment]
done in #115
